// <auto-generated />
using Levy_Calculator.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Levy_Calculator.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230314113252_Migration1")]
    partial class Migration1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Levy_Calculator.YearCoefficient", b =>
                {
                    b.Property<int>("Year")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Year"));

                    b.Property<double>("Coefficient")
                        .HasColumnType("float");

                    b.HasKey("Year");

                    b.ToTable("YearCoefficients");

                    b.HasData(
                        new
                        {
                            Year = 1965,
                            Coefficient = 5.0
                        },
                        new
                        {
                            Year = 1966,
                            Coefficient = 5.0
                        },
                        new
                        {
                            Year = 1967,
                            Coefficient = 5.0
                        },
                        new
                        {
                            Year = 1968,
                            Coefficient = 5.0
                        },
                        new
                        {
                            Year = 1969,
                            Coefficient = 5.0
                        },
                        new
                        {
                            Year = 1970,
                            Coefficient = 5.0
                        },
                        new
                        {
                            Year = 1971,
                            Coefficient = 5.0
                        },
                        new
                        {
                            Year = 1972,
                            Coefficient = 5.0
                        },
                        new
                        {
                            Year = 1973,
                            Coefficient = 5.0
                        },
                        new
                        {
                            Year = 1974,
                            Coefficient = 5.0
                        },
                        new
                        {
                            Year = 1975,
                            Coefficient = 5.0
                        },
                        new
                        {
                            Year = 1976,
                            Coefficient = 5.0
                        },
                        new
                        {
                            Year = 1977,
                            Coefficient = 5.0
                        },
                        new
                        {
                            Year = 1978,
                            Coefficient = 5.0
                        },
                        new
                        {
                            Year = 1979,
                            Coefficient = 5.0
                        },
                        new
                        {
                            Year = 1980,
                            Coefficient = 5.0
                        },
                        new
                        {
                            Year = 1981,
                            Coefficient = 5.0
                        },
                        new
                        {
                            Year = 1982,
                            Coefficient = 5.0
                        },
                        new
                        {
                            Year = 1983,
                            Coefficient = 5.0
                        },
                        new
                        {
                            Year = 1984,
                            Coefficient = 5.0
                        },
                        new
                        {
                            Year = 1985,
                            Coefficient = 5.0
                        },
                        new
                        {
                            Year = 1986,
                            Coefficient = 5.0
                        },
                        new
                        {
                            Year = 1987,
                            Coefficient = 5.0
                        },
                        new
                        {
                            Year = 1988,
                            Coefficient = 5.0
                        },
                        new
                        {
                            Year = 1989,
                            Coefficient = 5.0
                        },
                        new
                        {
                            Year = 1990,
                            Coefficient = 5.0
                        },
                        new
                        {
                            Year = 1991,
                            Coefficient = 5.0
                        },
                        new
                        {
                            Year = 1992,
                            Coefficient = 5.0
                        },
                        new
                        {
                            Year = 1993,
                            Coefficient = 5.0
                        },
                        new
                        {
                            Year = 1994,
                            Coefficient = 5.0
                        },
                        new
                        {
                            Year = 1995,
                            Coefficient = 5.0
                        },
                        new
                        {
                            Year = 1996,
                            Coefficient = 5.0
                        },
                        new
                        {
                            Year = 1997,
                            Coefficient = 5.0
                        },
                        new
                        {
                            Year = 1998,
                            Coefficient = 5.0
                        },
                        new
                        {
                            Year = 1999,
                            Coefficient = 5.0
                        },
                        new
                        {
                            Year = 2000,
                            Coefficient = 2.3999999999999999
                        },
                        new
                        {
                            Year = 2001,
                            Coefficient = 2.5
                        },
                        new
                        {
                            Year = 2002,
                            Coefficient = 2.7999999999999998
                        },
                        new
                        {
                            Year = 2003,
                            Coefficient = 3.0
                        },
                        new
                        {
                            Year = 2004,
                            Coefficient = 3.0
                        },
                        new
                        {
                            Year = 2005,
                            Coefficient = 3.0
                        },
                        new
                        {
                            Year = 2006,
                            Coefficient = 3.0
                        },
                        new
                        {
                            Year = 2007,
                            Coefficient = 3.0
                        },
                        new
                        {
                            Year = 2008,
                            Coefficient = 3.0
                        },
                        new
                        {
                            Year = 2009,
                            Coefficient = 3.0
                        },
                        new
                        {
                            Year = 2010,
                            Coefficient = 3.0
                        },
                        new
                        {
                            Year = 2011,
                            Coefficient = 3.0
                        },
                        new
                        {
                            Year = 2012,
                            Coefficient = 3.0
                        },
                        new
                        {
                            Year = 2013,
                            Coefficient = 3.0
                        },
                        new
                        {
                            Year = 2014,
                            Coefficient = 3.0
                        },
                        new
                        {
                            Year = 2015,
                            Coefficient = 3.0
                        },
                        new
                        {
                            Year = 2016,
                            Coefficient = 3.0
                        },
                        new
                        {
                            Year = 2017,
                            Coefficient = 3.0
                        },
                        new
                        {
                            Year = 2018,
                            Coefficient = 1.5
                        },
                        new
                        {
                            Year = 2019,
                            Coefficient = 1.5
                        },
                        new
                        {
                            Year = 2020,
                            Coefficient = 1.5
                        },
                        new
                        {
                            Year = 2021,
                            Coefficient = 1.5
                        },
                        new
                        {
                            Year = 2022,
                            Coefficient = 1.5
                        },
                        new
                        {
                            Year = 2023,
                            Coefficient = 1.3
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
